- .gitignore
- __tests__/epds-survey.test.js
- apollo-client.js
- pages/epds-survey.js
- pages/index.js
- pages/results.js
- src/constants/constants.js
- src/utils/tracker.utils.js
Ticket : https://github.com/SocialGouv/1000jours/issues/945
> feat(enregistrement): enregistrement des réponses

- pages/contact/contact-confirmed.js
- pages/contact/contact-form.js
- pages/contact/to-be-contacted.js
- pages/epds-survey.js
- pages/index.js
- pages/results.js
- src/components/WidgetHeader.js
- src/components/results/ContactMamanBlues.js
- src/components/survey/EpdsQuestion.js
- src/components/survey/SurveyCarousel.js
- src/components/survey/SurveyProgressBar.js
- styles/colors.scss
- styles/globals.scss
- styles/results.scss
Tickets : 
- https://github.com/SocialGouv/1000jours/issues/950
- https://github.com/SocialGouv/1000jours/issues/997
> feat(boutons): boutons de retour & review UI

- pages/contact/to-be-contacted.js
- pages/index.js
- pages/results.js
- styles/Home.module.css
- styles/beContacted.scss
- styles/globals.scss
- styles/results.scss
Ticket : https://github.com/SocialGouv/1000jours/issues/1024
> fix: retours UI

- __tests__/results.test.js
- pages/contact/contact-form.js
- pages/index.js
- src/constants/specificLabels.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1039
> fix: formulaire et doublons

- README.md
- __tests__/components/widget-header.test.js
- __tests__/index.test.js
- package.json
- pages/epds-survey.js
- pages/index.js
- src/components/ChooseEpdsLocale.js
- src/components/WidgetHeader.js
- src/components/survey/EpdsQuestion.js
- src/components/survey/SurveyCarousel.js
- src/constants/constants.js
- src/utils/main.utils.js
- styles/beContacted.scss
- styles/globals.scss
- styles/survey.scss
- yarn.lock
Ticket : https://github.com/SocialGouv/1000jours/issues/946
> feat(traduction): choix de la langue

- jest.config.js
- pages/contact/contact-confirmed.js
- pages/contact/contact-form.js
> fix: lints

- .github/workflows/preproduction.yml
- .github/workflows/review.yml
- __tests__/utils/main.utils.test.js
- pages/contact/contact-form.js
- pages/index.js
- src/utils/main.utils.js
- styles/colors.scss
- styles/globals.scss
- styles/results.scss
- styles/survey.scss
Tickets : 
- https://github.com/SocialGouv/1000jours/issues/1159
- https://github.com/SocialGouv/1000jours/issues/930
> feat(accueil): améliorations pour la visibilité

- pages/contact/to-be-contacted.js
- src/utils/tracker.utils.js
Lancer directement le chat lors de la validation plutôt que de passer par une modale
> fix(chat): lancer directement le chat

- pages/contact/to-be-contacted.js
Problème technique sur le chat, on cache le bouton pour ne pas donner de faux espoirs aux parents
> fix(chat): cacher le contact par chat

- pages/epds-survey.js
- styles/globals.scss
Ticket : https://github.com/SocialGouv/1000jours/issues/1288
> feat(epds): cacher consigne

- apollo-client.js
- pages/index.js
- pages/survey/before-survey.js
- styles/globals.scss
Ticket : https://github.com/SocialGouv/1000jours/issues/1311
Ticket : https://github.com/SocialGouv/1000jours/issues/1312
> fix(accueil): numbre exact de tests réalisé & bug

- src/constants/specificLabels.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1333
> fix(epds): maj consigne

- __tests__/pages/results.test.js
- __tests__/utils/ab-testing/mesuring-intentions.utils.test.js
- pages/ab-testing/demographic-data-survey.js
- pages/index.js
- pages/results.js
- src/components/ab-testing/intentions/MeasuringIntentions.js
- src/constants/constants.js
- src/utils/ab-testing/measuring-intentions.utils.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1351
> feat(test): suppr intentions et mettre UI du test C

- README.md
- __tests__/utils/ab-testing/ab-testing.utils.test.js
- __tests__/utils/ab-testing/demographic-data.utils.test.js
- __tests__/utils/ab-testing/mesuring-intentions.utils.test.js
- jest.setup.js
- pages/ab-testing/demographic-data-survey.js
- pages/contact/contact-confirmed.js
- pages/contact/contact-form.js
- pages/contact/to-be-contacted.js
- pages/index.js
- pages/results.js
- pages/survey/before-survey.js
- pages/survey/epds-survey.js
- src/components/ab-testing/intentions/FormToSendMail.js
- src/components/ab-testing/intentions/MeasuringIntentions.js
- src/components/ab-testing/intentions/TextAreaToSendDetails.js
- src/components/results/ContactMamanBlues.js
- src/constants/constants.js
- src/utils/ab-testing/ab-testing.utils.js
- src/utils/ab-testing/demographic-data.utils.js
- src/utils/ab-testing/measuring-intentions.utils.js
- src/utils/main.utils.js
- src/utils/storage.utils.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1348
> feat(demographie): mise en place test A/B/C

- pages/results.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1348
> fix(intentions): bloc si score < 11

- package.json
- pages/contact/to-be-contacted.js
- yarn.lock
Ticket : https://github.com/SocialGouv/1000jours/issues/1231
> feat(chat): activation chat

- pages/index.js
- src/utils/ab-testing/measuring-intentions.utils.js
- src/utils/tracker.utils.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1444
> fix: trackers

- __tests__/components/ab-testing/measuring-intentions.test.js
- next.config.js
- pages/_app.js
- pages/ab-testing/demographic-data-survey.js
- pages/contact/contact-form.js
- pages/contact/to-be-contacted.js
- pages/survey/before-survey.js
- pages/survey/epds-survey.js
- src/components/CarouselCustom.js
- src/components/ChooseEpdsLocale.js
- src/components/JobSelector.js
- src/components/LocaleButton.js
- src/components/WidgetHeader.js
- src/components/results/ContactMamanBlues.js
- src/components/results/ResultsMood.js
- src/components/survey/EpdsQuestion.js
- src/components/survey/SurveyProgressBar.js
- styles/beContacted.scss
- styles/globals.scss
- styles/survey.scss
Ticket : https://github.com/SocialGouv/1000jours/issues/1449
> feat: accessibilité

- pages/results.js
- src/utils/tracker.utils.js
- styles/colors.scss
- styles/results.scss
Ticket : https://github.com/SocialGouv/1000jours/issues/1472
> feat(avis): ajout opinion

- apollo-client.js
- pages/ab-testing/demographic-data-survey.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1480
> feat(demographie): ajout nom du département

- pages/results.js
- src/components/results/Intentions.js
- styles/results.scss
Tickets : 
- https://github.com/SocialGouv/1000jours/issues/1463
- https://github.com/SocialGouv/1000jours/issues/1519
> fix(intentions):  retours de démo

- __tests__/utils/contact.utils.test.js
- pages/contact/contact-confirmed.js
- pages/contact/contact-form.js
- pages/contact/to-be-contacted.js
- src/utils/contact.utils.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1504
> fix(matomo): doublons pour la confirmation de contact

- src/components/results/Intentions.js
- src/components/results/RecruitParents.js
- src/utils/tracker.utils.js
- styles/results.scss
Ticket : https://github.com/SocialGouv/1000jours/issues/1522
> feat(recrutement): modal pour demander aux parents

- __tests__/utils/ab-testing/ab-testing.utils.test.js
- __tests__/utils/ab-testing/contact-button-label.utils.test.js
- src/components/results/ContactMamanBlues.js
- src/utils/ab-testing/ab-testing.utils.js
- src/utils/ab-testing/contact-button-label.utils.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1497
> feat(contact): ab testing sur le bonton de contact

- apollo-client.js
- pages/ab-testing/demographic-data-survey.js
- pages/contact/contact-form.js
- pages/contact/to-be-contacted.js
- pages/survey/epds-survey.js
- src/utils/contact.utils.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1521
> feat(contact): ajout query

- pages/contact/to-be-contacted.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1536
> feat(chat): enabled variable

- README.md
- __tests__/utils/ab-testing/ab-testing.utils.test.js
- __tests__/utils/contact.utils.test.js
- pages/contact/to-be-contacted.js
- pages/index.js
- pages/results.js
- pages/survey/epds-survey.js
- src/components/results/ContactMamanBlues.js
- src/components/results/RecruitParents.js
- src/utils/ab-testing/ab-testing.utils.js
- src/utils/ab-testing/demographic-data.utils.js
- src/utils/ab-testing/measuring-intentions.utils.js
- src/utils/contact.utils.js
- src/utils/tracker.utils.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1541
> fix(matomo): trackers + refacto

- __tests__/components/carousel-custom.test.js
- __tests__/components/department-code-selector.test.js
- __tests__/pages/ab-testing/demographic-data-survey.test.js
- __tests__/utils/ab-testing/demographic-data.utils.test.js
- pages/ab-testing/demographic-data-survey.js
- src/components/DepartmentCodeSelector.js
- src/components/DeptCodeSelector.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1534
> feat(demographie): simplifier dept

- csv/departments-com.csv
- pages/api/staticDepartmentComData.js
- src/components/DepartmentCodeSelector.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1534
> feat(demographie): ajout dom

- pages/results.js
- src/components/results/Intentions.js
- src/components/results/RecruitParents.js
- src/utils/ab-testing/ab-testing.utils.js
- src/utils/main.utils.js
- styles/results.scss
Ticket : https://github.com/SocialGouv/1000jours/issues/1555
> feat(resultats): maj recrutement parents et opinion

- package.json
- pages/survey/epds-survey.js
- src/constants/constants.js
- yarn.lock
Ticket : https://github.com/SocialGouv/1000jours/issues/1560
> feat(epds): ajout crisp

- pages/index.js
- pages/survey/epds-survey.js
- src/utils/contact.utils.js
- src/utils/tracker.utils.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1561
> feat(matomo): trackers génériques

- __tests__/components/ab-testing/measuring-intentions.test.js
- src/components/results/ContactMamanBlues.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1567
> feat(abtesting): suppression sur le bt contacter

- pages/contact/to-be-contacted.js
Ticket : https://github.com/SocialGouv/1000jours/issues/1531
> feat(chat): poc crisp

- .kontinuous/env/prod/values.yaml
add requests and limits
remove autosacale
> fix:1000jbluesepdsWidget-resources
